const fs = require('fs');
const p = 'c:/Users/party/Desktop/JuegoDemo/js/render/spectralEnemies2D.js';
let s = '';
s += '  function drawEyes(ctx, e, player, profile) {\n';
s += '    if (!player) return;\n';
s += '    const r = e.radius * (profile.radiusMul || 1);\n';
s += '    const fwd = Math.atan2(player.y - e.y, player.x - e.x);\n';
s += '    const eyeR = Math.max(1.4, r * 0.17);\n';
s += '    const sep = r * 0.32;\n';
s += "    const pupil = profile.elite ? '#ff2222' : '#10131c';\n";
s += "    if (profile.eyeStyle === 'single') {\n";
s += "      ctx.fillStyle = '#fff'; ctx.beginPath(); ctx.arc(0, 0, eyeR, 0, Math.PI * 2); ctx.fill();\n";
s += "      ctx.fillStyle = pupil; ctx.beginPath(); ctx.arc(Math.cos(fwd) * eyeR * 0.4, Math.sin(fwd) * eyeR * 0.4, eyeR * 0.5, 0, Math.PI * 2); ctx.fill();\n";
s += "    } else if (profile.eyeStyle === 'narrow') {\n";
s += '      for (const side of [-1, 1]) {\n';
s += '        const ex = side * sep * 0.45, ey = -r * 0.08;\n';
s += "        ctx.fillStyle = '#fff'; ctx.beginPath(); ctx.ellipse(ex, ey, eyeR * 0.7, eyeR * 0.45, fwd, 0, Math.PI * 2); ctx.fill();\n";
s += "        ctx.fillStyle = pupil; ctx.beginPath(); ctx.arc(ex + Math.cos(fwd) * eyeR * 0.3, ey + Math.sin(fwd) * eyeR * 0.3, eyeR * 0.3, 0, Math.PI * 2); ctx.fill();\n";
s += '      }\n';
s += "    } else if (profile.eyeStyle === 'asymmetric') {\n";
s += "      ctx.fillStyle = '#fff';\n";
s += "      ctx.beginPath(); ctx.arc(-sep * 0.3, -r * 0.05, eyeR * 0.8, 0, Math.PI * 2); ctx.fill();\n";
s += "      ctx.beginPath(); ctx.arc(sep * 0.4, -r * 0.02, eyeR * 1.0, 0, Math.PI * 2); ctx.fill();\n";
s += '      ctx.fillStyle = pupil;\n';
s += "      ctx.beginPath(); ctx.arc(-sep * 0.3 + Math.cos(fwd) * eyeR * 0.3, -r * 0.05 + Math.sin(fwd) * eyeR * 0.3, eyeR * 0.35, 0, Math.PI * 2); ctx.fill();\n";
s += "      ctx.beginPath(); ctx.arc(sep * 0.4 + Math.cos(fwd) * eyeR * 0.4, -r * 0.02 + Math.sin(fwd) * eyeR * 0.4, eyeR * 0.45, 0, Math.PI * 2); ctx.fill();\n";
s += '    } else {\n';
s += '      for (const side of [-1, 1]) {\n';
s += '        const ex = side * sep * 0.5, ey = -r * 0.05;\n';
s += "        ctx.fillStyle = '#fff'; ctx.beginPath(); ctx.arc(ex, ey, eyeR, 0, Math.PI * 2); ctx.fill();\n";
s += "        ctx.fillStyle = pupil; ctx.beginPath(); ctx.arc(ex + Math.cos(fwd) * eyeR * 0.45, ey + Math.sin(fwd) * eyeR * 0.45, eyeR * 0.5, 0, Math.PI * 2); ctx.fill();\n";
s += '      }\n';
s += '    }\n';
s += '  }\n';
s += '  function drawStatusLayers(ctx, e, frame, player, profile) {\n';
s += '    if (e.slowUntil > 0) {\n';
s += '      const t = frame * 0.06;\n';
s += '      const cold = 0.5 + Math.sin(t * 3.5) * 0.5;\n';
s += "      ctx.fillStyle = 'rgba(103,232,249,' + (cold * 0.22) + ')';\n";
s += '      ctx.beginPath(); ctx.arc(0, 0, e.radius, 0, Math.PI * 2); ctx.fill();\n';
s += '    }\n';
s += '    if (e.mine) {\n';
s += "      ctx.strokeStyle = 'rgba(255,215,95,0.7)'; ctx.lineWidth = 1.5;\n";
s += '      for (let i = 0; i < 4; i++) {\n';
s += '        const a = (i / 4) * Math.PI * 2 + frame * 0.03;\n';
s += '        ctx.beginPath(); ctx.moveTo(Math.cos(a) * (e.radius + 3), Math.sin(a) * (e.radius + 3)); ctx.lineTo(Math.cos(a) * (e.radius + 8), Math.sin(a) * (e.radius + 8)); ctx.stroke();\n';
s += '      }\n';
s += '    }\n';
s += '    if (e.armed) {\n';
s += '      const blink = 0.4 + Math.sin(frame * 0.36) * 0.6;\n';
s += "      ctx.globalAlpha = blink; ctx.fillStyle = '#fff';\n";
s += '      ctx.beginPath(); ctx.arc(0, 0, e.radius * 0.5, 0, Math.PI * 2); ctx.fill();\n';
s += '      ctx.globalAlpha = 1;\n';
s += '    }\n';
s += '    if (e.isElite) {\n';
s += '      ctx.globalAlpha = 0.6 + Math.sin(frame * 0.12) * 0.3;\n';
s += "      ctx.strokeStyle = '#ffd700'; ctx.lineWidth = 2.5;\n";
s += '      ctx.beginPath(); ctx.arc(0, 0, e.radius + 5, 0, Math.PI * 2); ctx.stroke();\n';
s += '      ctx.globalAlpha = 1;\n';
s += '    }\n';
s += '    if (e.atkFlash > 0 && player) {\n';
s += '      const r = e.radius;\n';
s += '      const atk = Math.min(1, Math.max(0, e.atkFlash / 0.45));\n';
s += '      const fwd = Math.atan2(player.y - e.y, player.x - e.x);\n';
s += "      ctx.strokeStyle = '#fff'; ctx.lineWidth = 4;\n";
s += '      ctx.beginPath(); ctx.arc(0, 0, r + 5, 0, Math.PI * 2); ctx.stroke();\n';
s += "      ctx.strokeStyle = '#ff3040'; ctx.lineWidth = 5;\n";
s += '      ctx.beginPath(); ctx.arc(0, 0, r + 8 + (1 - atk) * 18, fwd + 1.1 + (1 - atk) * 0.45, fwd - 1.1 - (1 - atk) * 0.45, true); ctx.stroke();\n';
s += '    }\n';
s += '  }\n';
s += '  NV.drawSpectralEnemy2D = function (ctx, e, frame, player, rhythm) {\n';
s += "    if (!e || e.dead || e.shape === 'specter') return false;\n";
s += '    const profile = resolveProfile(e);\n';
s += '    ctx.save();\n';
s += '    let rx = 0, ry = 0;\n';
s += "    if (rhythm && rhythm.enabled && rhythm.state === 'listening') {\n";
s += '      const sig = Math.min(1, (rhythm.bass || 0) * 0.5 + (rhythm.kick || 0) * 0.7);\n';
s += '      const thr = 0.18 + hash01(e, 1) * 0.52;\n';
s += '      const level = Math.max(0, Math.min(1, (sig - thr) / (1 - thr)));\n';
s += '      if (level > 0.02 && ((rhythm.onset || 0) > 0.05 || (rhythm.kick || 0) > 0.05)) {\n';
s += '        const seed = hash01(e, 2) * 6.28318;\n';
s += '        const amp = Math.min(4.5, (0.9 + sig * 3.4) * level);\n';
s += '        rx = Math.sin((frame || 0) * 0.31 + seed) * amp;\n';
s += '        ry = Math.cos((frame || 0) * 0.27 + seed * 1.7) * amp * 0.62;\n';
s += '      }\n';
s += '    }\n';
s += '    ctx.translate(e.x + rx, e.y + ry);\n';
s += '    drawStatusLayers(ctx, e, frame, player, profile);\n';
s += '    drawBody(ctx, e, frame, profile);\n';
s += '    drawEyes(ctx, e, player, profile);\n';
s += '    ctx.restore();\n';
s += '    return true;\n';
s += '  };\n';
s += '  NV.drawSpectralBoss2D = function () { return false; };\n';
s += '  NV.SPECTRAL_ENEMY_PROFILES = PROFILES;\n';
s += '})();\n';
fs.appendFileSync(p, s, 'utf8');
console.log('API_OK');