const fs=require('fs'),vm=require('vm'); let pass=0,fail=0; function t(n,f){try{f();pass++;console.log('  ok  '+n)}catch(e){fail++;console.log('  FAIL '+n+' -> '+e.message)}}
const NV={}; vm.runInNewContext(fs.readFileSync('js/render/metaReadability.js','utf8'),{window:{NV},Map,WeakMap,Math});
t('campo distingue masa comprimida de enemigos aislados',()=>{const dense=Array.from({length:8},(_,i)=>({x:100+i,y:100,radius:10})); const lone={x:500,y:400,radius:10}; const f=NV.buildDensityField(dense.concat(lone)); if(!(f.info.get(dense[0]).intensity>f.info.get(lone).intensity))throw Error('sin contraste');});
t('spatial grid evita comparación cuadrática en 80 dispersos',()=>{const es=Array.from({length:80},(_,i)=>({x:(i%10)*200,y:Math.floor(i/10)*200,radius:10})); const f=NV.buildDensityField(es); if(f.comparisons>300)throw Error('comparaciones='+f.comparisons);});
t('cálculo no muta objetos de gameplay',()=>{const e={x:1,y:2,radius:10};const before=JSON.stringify(e);NV.buildDensityField([e]);if(JSON.stringify(e)!==before)throw Error('mutó');});
t('render de densidad es conservador y contextual',()=>{const calls=[];const ctx=new Proxy({save(){},restore(){},beginPath(){},arc(){calls.push('arc')},stroke(){}},{set(){return true}}); if(NV.drawEnemyDensity(ctx,{radius:10},{intensity:.1,overlap:0}))throw Error('dibujó baja'); if(!NV.drawEnemyDensity(ctx,{radius:10},{intensity:.8,overlap:1}))throw Error('no dibujó alta');});
t('contacto se muestra solo cerca/ataque o completo en debug',()=>{const ctx=new Proxy({save(){},restore(){},beginPath(){},arc(){},stroke(){},setLineDash(){}},{set(){return true}}),p={x:0,y:0}; if(NV.drawContactReadability(ctx,{x:200,y:0,radius:10},p,false))throw Error('lejano visible'); if(!NV.drawContactReadability(ctx,{x:35,y:0,radius:10},p,false))throw Error('cercano oculto'); if(!NV.drawContactReadability(ctx,{x:200,y:0,radius:10},p,true))throw Error('debug oculto');});
t('feedback de daño separa impacto e invulnerabilidad',()=>{const ctx=new Proxy({save(){},restore(){},beginPath(){},arc(){},stroke(){},moveTo(){},lineTo(){}},{set(){return true}}),p={x:10,y:10};if(!NV.drawDamageFeedback(ctx,p,{life:.4,sourceX:0,sourceY:10,critical:false}))throw Error('sin impacto');if(!NV.drawInvulnerabilityFeedback(ctx,p,{life:.2,duration:.5,kind:'start'}))throw Error('sin invuln');});
t('momentum usa velocidad real y no teclas de dirección',()=>{const lines=[];const ctx=new Proxy({save(){},restore(){},beginPath(){},stroke(){},moveTo(){},lineTo(x,y){lines.push([x,y])}},{set(){return true}});if(NV.drawMomentumReadability(ctx,{x:0,y:0,moveVx:10,moveVy:0},{shift:true,previousSpeed:0}))throw Error('dibujó lento');if(!NV.drawMomentumReadability(ctx,{x:0,y:0,moveVx:300,moveVy:0},{shift:true,previousSpeed:0}))throw Error('no dibujó rápido');if(!lines.length)throw Error('sin vector');});
t('target autofire usa micro-retícula discreta',()=>{let strokes=0;const ctx=new Proxy({save(){},restore(){},beginPath(){},stroke(){strokes++},moveTo(){},lineTo(){}},{set(){return true}});if(NV.drawAutofireTarget(ctx,null,0))throw Error('dibujó null');if(!NV.drawAutofireTarget(ctx,{x:10,y:10,radius:8},0)||strokes!==4)throw Error('retícula incorrecta');});
console.log('RESULT meta_density: pass='+pass+' fail='+fail);process.exit(fail?1:0);